swagger: '2.0'
info:
  description: 'SpareMoney API Document'
  version: '1.0.0'
  title: 'SpareMoney'
host: '118.89.65.154:8765'
basePath: '/'

tags:
- name: 'Account'
  description: '账户'
- name: 'Assignment'
  description: '任务'
- name: 'Questionnaire'
  description: '问卷'
- name: 'Question & Answer'
  description: '懂了么'
- name: 'Coin'
  description: '闲钱'
- name: 'System'
  description: '系统'
schemes:
- 'http'

paths:
  /account/:
    post:
      tags:
      - 'Account'
      summary: '注册账户'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
      - in: 'body'
        name: 'body'
        description: '账户注册必要信息'
        required: true
        schema:
          type: 'object'
          properties:
            email:
              type: 'string'
              example: 'mmm@qq.com'
            password:
              type: 'string'
              example: '123456'
            gender:
              type: 'string'
              enum:
              - 'male'
              - 'female'
            nickname:
              type: 'string'
              example: 'ljm'
      responses:
        200:
          description: 'ok, 返回uid信息'
          schema:
            $ref: '#/definitions/RegisterResponse'
          
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /account/self:
    get:
      tags:
      - 'Account'
      summary: '获取自身账户信息'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/UserInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

    put:
      tags:
      - 'Account'
      summary: '修改自身账户基本信息'
      parameters:
      - in: 'body'
        name: 'body'
        description: '账户信息'
        required: true
        schema:
          type: 'object'
          properties:
            # password:
            #   type: 'string'
            # class:
            #   type: 'integer'
            gender:
              type: 'string'
              enum:
              - 'male'
              - 'female'
            nickname:
              type: 'string'
              example: 'ljm'
            grade:
              type: 'string'
              example: '2016'
            college:
              type: 'string'
              example: 'sysu'
            major:
              type: 'string'
              example: 'SE'
            studentID:
              type: 'integer'
              example: 16340115
            realname:
              type: 'string'
              example: 'ljm'

      responses:
        200:
          description: 'ok'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /account/password:
    put:
      tags:
      - 'Account'
      summary: '修改自身账户密码'
      parameters:
      - in: 'body'
        name: 'body'
        description: '账户新旧密码'
        required: true
        schema:
          type: 'object'
          properties:
            old_password:
              type: 'string'
              example: '123456'
            new_password:
              type: 'string'
              example: '1234567'

      responses:
        200:
          description: 'ok'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /account/avatar:
    post:
      tags:
      - 'Account'
      summary: '修改自身账户头像'
      consumes:
      - 'multipart/form-data'
      produces:
      - 'application/json'
      parameters:
      - in: 'formData'
        name: 'file'
        type: 'file'
        description: '账户新头像'
        required: true

      responses:
        200:
          description: 'ok, 返回头像url信息'
          schema:
            $ref: '#/definitions/ImageURLResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'


  /account/{uid}:
    get:
      tags:
      - 'Account'
      summary: '获取id为uid的账户信息'
      parameters:
      - name: 'uid'
        in: 'path'
        required: true
        description: 'uid'
        type: 'integer'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/UserInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /system/image:
    post:
      tags:
      - 'System'
      summary: '上传图片'
      consumes:
      - 'multipart/form-data'
      parameters:
      - in: 'formData'
        name: 'image'
        type: 'file'
        description: '图片'
        required: true
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/ImageURLResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'
  
  /account/session:
    post:
      tags:
      - 'Account'
      summary: '登录'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
      - in: 'body'
        name: 'body'
        description: '登录信息'
        required: true
        schema:
          $ref: '#/definitions/LoginRequest'
      responses:
        200:
          description: 'ok, 返回uid信息'
          schema:
            $ref: '#/definitions/IdResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

    delete:
      tags:
      - 'Account'
      summary: '登出'
      produces:
      - 'application/json'
      responses:
        200:
          description: 'ok'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /assignment:
    get:
      tags:
      - 'Assignment'
      summary: '获取最近20个任务'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/AssignmentInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /assignment/{pages}:
    get:
      tags:
      - 'Assignment'
      summary: '获取第pages页的20个任务'
      parameters:
      - name: 'pages'
        in: 'path'
        required: true
        description: '页数'
        type: 'integer'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/AssignmentInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /assignment/questionnaire:
    get:
      tags:
      - 'Assignment'
      summary: '获取最近20个问卷'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/AssignmentQInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /assignment/questionnaire/{pages}:
    get:
      tags:
      - 'Assignment'
      summary: '获取第pages页的20个问卷'
      parameters:
      - name: 'pages'
        in: 'path'
        required: true
        description: '页数'
        type: 'integer'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/AssignmentQInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /assignment/qa:
    get:
      tags:
      - 'Assignment'
      summary: '获取最近20个懂了么'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/AssignmentQAInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /assignment/qa/{pages}:
    get:
      tags:
      - 'Assignment'
      summary: '获取第pages页的20个懂了么'
      parameters:
      - name: 'pages'
        in: 'path'
        required: true
        description: '页数'
        type: 'integer'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/AssignmentQAInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /assignment/self/{type}:
    get:
      tags:
      - 'Assignment'
      summary: '获取自身任务信息'
      parameters:
      - name: 'type'
        in: 'path'
        required: true
        description: '类型, {"all", "questionnaire", "qa", "answer"}'
        type: 'string'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/AssignmentInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /questionnaire/{aid}:
    get:
      tags:
      - 'Questionnaire'
      summary: '获取id=aid的问卷'
      parameters:
      - name: 'aid'
        in: 'path'
        required: true
        description: 'aid'
        type: 'integer'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/QuestionnaireInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

    post:
      tags:
      - 'Questionnaire'
      summary: '提交问卷'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
      - name: 'aid'
        in: 'path'
        required: true
        description: 'aid'
        type: 'integer'
      - in: 'body'
        name: 'body'
        description: '问卷答案信息'
        required: true
        schema:
          $ref: '#/definitions/QuestionnaireAnsRequest'
      responses:
        200:
          description: 'ok'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

    delete:
      tags:
      - 'Questionnaire'
      summary: '删除自己创建的问卷'
      produces:
      - 'application/json'
      parameters:
      - name: 'aid'
        in: 'path'
        required: true
        description: 'aid'
        type: 'integer'
      responses:
        200:
          description: 'ok'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /questionnaire:
    post:
      tags:
      - 'Questionnaire'
      summary: '发布一个问卷类型的任务'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
      - in: 'body'
        name: 'body'
        description: '问卷类型的任务信息'
        required: true
        schema:
          $ref: '#/definitions/QuestionnaireInfoRequest'
      responses:
        200:
          description: 'ok, 返回任务aid'
          schema:
            $ref: '#/definitions/IdResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /questionnaire/answer/{aid}:
    get:
      tags:
      - 'Questionnaire'
      summary: '获取id=aid的问卷统计答案'
      parameters:
      - name: 'aid'
        in: 'path'
        required: true
        description: 'aid'
        type: 'integer'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/AnswerInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /qa/{aid}:
    get:
      tags:
      - 'Question & Answer'
      summary: '获取id=aid的懂了么'
      parameters:
      - name: 'aid'
        in: 'path'
        required: true
        description: 'aid'
        type: 'integer'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/QAInfoResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

    post:
      tags:
      - 'Question & Answer'
      summary: '回答懂了么'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
      - name: 'aid'
        in: 'path'
        required: true
        description: 'aid'
        type: 'integer'
      - in: 'body'
        name: 'body'
        description: '懂了么回答信息'
        required: true
        schema:
          $ref: '#/definitions/QAnswerRequest'
      responses:
        200:
          description: 'ok 返回回答qaid信息'
          #schema:
            #$ref: '#/definitions/IdResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

    delete:
      tags:
      - 'Question & Answer'
      summary: '删除自己创建的懂了么'
      produces:
      - 'application/json'
      parameters:
      - name: 'aid'
        in: 'path'
        required: true
        description: 'aid'
        type: 'integer'
      responses:
        200:
          description: 'ok'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /qa/:
    post:
      tags:
      - 'Question & Answer'
      summary: '发布一个懂了么的任务'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
      - in: 'body'
        name: 'body'
        description: '懂了么的任务信息'
        required: true
        schema:
          $ref: '#/definitions/QAInfoRequest'
      responses:
        200:
          description: 'ok, 返回任务aid'
          schema:
            $ref: '#/definitions/IdResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  # /qa/best/{aid}:
  #   delete:
  #     tags:
  #     - 'Question & Answer'
  #     summary: '取消采纳懂了么回答'
  #     produces:
  #     - 'application/json'
  #     parameters:
  #     - name: 'aid'
  #       in: 'path'
  #       required: true
  #       description: '懂了么任务的aid'
  #       type: 'integer'
  #     responses:
  #       200:
  #         description: 'ok'
  #       400:
  #         description: 'fail'
  #         schema:
  #           $ref: '#/definitions/ErrorResponse'

  /qa/{aid}/{qaid}:
    put:
      tags:
      - 'Question & Answer'
      summary: '采纳懂了么回答'
      produces:
      - 'application/json'
      parameters:
      - name: 'aid'
        in: 'path'
        required: true
        description: '懂了么的aid'
        type: 'integer'
      - name: 'qaid'
        in: 'path'
        required: true
        description: '懂了么回答的qaid'
        type: 'integer'
      responses:
        200:
          description: 'ok'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

    delete:
      tags:
      - 'Question & Answer'
      summary: '删除懂了么回答'
      produces:
      - 'application/json'
      parameters:
      - name: 'qaid'
        in: 'path'
        required: true
        description: '懂了么回答的qaid'
        type: 'integer'
      responses:
        200:
          description: 'ok'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /coin/self:
    get:
      tags:
      - 'Coin'
      summary: '获取自身闲钱数量'
      responses:
        200:
          description: 'ok'
          schema:
            $ref: '#/definitions/CoinResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

    post:
      tags:
      - 'Coin'
      summary: '充值100闲钱'
      responses:
        200:
          description: 'ok, 返回闲钱数'
          schema:
            $ref: '#/definitions/CoinResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

    delete:
      tags:
      - 'Coin'
      summary: '不小心弄丢50闲钱'
      responses:
        200:
          description: 'ok, 返回闲钱数'
          schema:
            $ref: '#/definitions/CoinResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

  /coin/{uid}:
    post:
      tags:
      - 'Coin'
      summary: '给予一些闲钱'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
      - in: 'body'
        name: 'body'
        description: '闲钱数量'
        required: true
        schema:
          $ref: '#/definitions/CoinRequest'
      responses:
        200:
          description: 'ok, 返回剩余闲钱'
          schema:
            $ref: '#/definitions/CoinResponse'
        400:
          description: 'fail'
          schema:
            $ref: '#/definitions/ErrorResponse'

definitions:

  ErrorResponse:
    type: 'object'
    properties:
      msg:
        type: 'string'

  User:
    type: 'object'
    properties:
      Email:
        type: 'string'
        example: '173717610@qq.com'
      # class:
      #   type: 'integer'
      Gender:
        type: 'string'
        example: 'male'
      Nickname:
        type: 'string'
        example: 'ljm'
      Avatar:
        type: 'string'
        example: '/media/avatar/default.jpg'
        description: "头像的url,通过118.89.65.154:8765/media/avatar/default.jpg访问"
      Grade:
        type: 'string'
        example: '2018'
      College:
        type: 'string'
        example: 'sysu'
      Major:
        type: 'string'
        example: 'SE'
      StudentID:
        type: 'integer'
        example: 16340115
      RealName:
        type: 'string'
        example: 'ljm'

  UserInfo:
    allOf:
    - properties:
        Uid:
          type: 'integer'
          example: 4
    - $ref: '#/definitions/User'
    
  UserInfoResponse:
    properties:
      data:
        $ref: '#/definitions/UserInfo'

  OtherUserInfoResponse:
    type: 'object'
    properties:
      class:
        type: 'integer'
      nickname:
        type: 'string'
      avatar:
        type: 'string'
      grade:
        type: 'string'
      college:
        type: 'string'
      major:
        type: 'string'
      studentID:
        type: 'string'


  ImageURLResponse:
    type: 'object'
    properties:
      url:
        type: 'string'
        example: '/media/avatar/20190612045125_87.jpg'
        description: "头像的url,通过118.89.65.154:8765/media/avatar/20190612045125_87.jpg访问"

  LoginRequest:
    type: 'object'
    properties:
      email:
        type: 'string'
        example: 'mmm@qq.com'
      password:
        type: 'string'
        example: '123456'

  AssignmentInfoResponse:
    type: 'object'
    properties:
      asgCount:
        type: 'integer'
        example: 1
        description: "所有页的总份数，可以用于分页"
      assignments:
        type: 'array'
        items:
          type: 'object'
          properties:
            title:
              type: 'string'
              example: 'Vue怎么写'
            description:
              type: 'string'
              example: '请教教我写Vue'
            type: 
              type: 'string'
              enum:
              - 'questionnaire'
              - 'qa'
              example: 'qa'
            aid:
              type: 'integer'
              example: 1
              description: "对应的任务id"
            creator:
              type: 'string'
              example: 'm'
            coin:
              type: 'integer'
              example: 99
              description: "总价"
            unit:
              type: 'integer'
              example: 5  
              description: "单价,与QA无关"
            createTime:
              type: 'string'
              example: "2019-06-11 20:44:21"
            startTime:
              type: 'string'
              example: "2019-06-11 21:45:21"
            endTime:
              type: 'string'
              example: "2020-06-12 20:44:21"
            answerCount:
              type: 'integer'
              example: 2
              description: "QA答案的数量，问卷可以不管"
            bestCount:
              type: 'integer'
              example: 1
              description: "0或1，是否有最佳答案，问卷可以不管"
            copy:
              type: 'integer'
              example: 0
              description: "问卷总共发布多少份，问答可以不管"            
        example:
          - title: 'Vue怎么写'
            description: '请教教我写Vue'
            type: 'qa'
            aid: 1
            creator: 'm'
            coin: 99
            unit: 5  
            createTime: "2019-06-11 20:44:21"
            startTime: "2019-06-11 21:45:21"
            endTime: "2020-06-12 20:44:21"
            answerCount: 2
            bestCount: 1
            copy: 0
          - title: '定向越野报名表'
            description: 'sdcs定向越野'
            type: 'questionnaire'
            aid: 2
            creator: 'm'
            coin: 100
            unit: 5  
            createTime: "2019-06-11 20:44:21"
            startTime: "2019-06-11 21:45:21"
            endTime: "2020-06-13 20:44:21"
            answerCount: 0
            bestCount: 0
            copy: 20

  

  AssignmentQInfoResponse:
    type: 'object'
    properties:
      asgCount:
        type: 'integer'
        example: 2
        description: "所有页里问卷的总份数，可以用于分页"
      assignments:
        type: 'array'
        items:
          type: 'object'
          properties:
            title:
              type: 'string'
              example: '定向越野报名表'
            description:
              type: 'string'
              example: 'sdcs定向越野'
            type: 
              type: 'string'
              enum:
              - 'questionnaire'
            aid:
              type: 'integer'
              example: 2
              description: "对应的任务id"
            creator:
              type: 'string'
              example: 'm'
            coin:
              type: 'integer'
              example: 100
              description: "总价"
            unit:
              type: 'integer'
              example: 5  
              description: "单价"
            createTime:
              type: 'string'
              example: "2019-06-11 20:44:21"
            startTime:
              type: 'string'
              example: "2019-06-11 21:45:21"
            endTime:
              type: 'string'
              example: "2020-06-11 20:44:21"
            answerCount:
              type: 'integer'
              example: 0
              description: "QA答案的数量，问卷可以不管"
            bestCount:
              type: 'integer'
              example: 0
              description: "0或1，是否有最佳答案，问卷可以不管"
            copy:
              type: 'integer'
              example: 0
              description: "问卷总共发布多少份，问答可以不管"   
        example:
          - title: '定向越野报名表2'
            description: 'sdcs定向越野2'
            type: 'questionnaire'
            aid: 5
            creator: 'm'
            coin: 200
            unit: 5  
            createTime: "2019-06-11 20:44:21"
            startTime: "2019-06-11 21:45:21"
            endTime: "2020-06-12 20:44:21"
            answerCount: 0
            bestCount: 0
            copy: 20
          - title: '定向越野报名表'
            description: 'sdcs定向越野'
            type: 'questionnaire'
            aid: 2
            creator: 'm'
            coin: 100
            unit: 5  
            createTime: "2019-06-11 20:44:21"
            startTime: "2019-06-11 21:45:21"
            endTime: "2020-06-13 20:44:21"
            answerCount: 0
            bestCount: 0
            copy: 100

  AssignmentQAInfoResponse:
    type: 'object'
    properties:
      asgCount:
        type: 'integer'
        example: 1
        description: "所有页里问卷的总份数，可以用于分页"
      assignments:
        type: 'array'
        items:
          type: 'object'
          properties:
            title:
              type: 'string'
              #example: 'Vue怎么写'
            description:
              type: 'string'
              #example: '请教教我写Vue'
            type: 
              type: 'string'
              enum:
              - 'qa'
            aid:
              type: 'integer'
              #example: 1
              description: "对应的任务id"
            creator:
              type: 'string'
              #example: 'm'
            coin:
              type: 'integer'
              #example: 99
              description: "总价"
            unit:
              type: 'integer'
              #example: 5  
              description: "单价,与QA无关"
            createTime:
              type: 'string'
              #example: "2019-06-11 20:44:21"
            startTime:
              type: 'string'
              #example: "2019-06-11 21:45:21"
            endTime:
              type: 'string'
              #example: "2020-06-11 20:44:21"
            answerCount:
              type: 'integer'
              #example: 2
              description: "QA答案的数量，问卷可以不管"
            bestCount:
              type: 'integer'
              #example: 1
              description: "0或1，是否有最佳答案，问卷可以不管"
            copy:
              type: 'integer'
              example: 0
              description: "问卷总共发布多少份，问答可以不管"   
        example:
          - title: 'Vue怎么写'
            description: '请教教我写Vue'
            type: 'qa'
            aid: 1
            creator: 'm'
            coin: 99
            unit: 5  
            createTime: "2019-06-11 20:44:21"
            startTime: "2019-06-11 21:45:21"
            endTime: "2020-06-12 20:44:21"
            answerCount: 2
            bestCount: 1
            copy: 0
          - title: 'python怎么写'
            description: '请教教我写python'
            type: 'qa'
            aid: 4
            creator: 'm'
            coin: 100
            unit: 5  
            createTime: "2019-06-11 20:44:21"
            startTime: "2019-06-11 21:45:21"
            endTime: "2020-06-13 20:44:21"
            answerCount: 4
            bestCount: 0
            copy: 0

  Question:
    type: 'object'
    properties:
      qid:
        type: 'integer'
        example: 1
      title:
        type: 'string'
        example: '性别'
      aid:
        type: 'integer'
        example: 2
        description: "对应的任务id"
      type:
        type: 'string'
        enum:
        - 'single'
        - 'multi'
        - 'input'
        example: 'input'

  QuestionRequest:
    type: 'object'
    properties:
      title:
        type: 'string'
        example: '李泓睿是男的还是女的'
      type:
        type: 'string'
        enum:
        - 'single'
        - 'multi'
        - 'input'
        example: 'single'

  Option:
    type: 'object'
    properties:
      oid:
        type: 'integer'
        #example: 1
      value:
        type: 'string'
        #example: '男'
      qid:
        type: 'integer'
        #example: 1
        description: '对应的问题id'
      aid:
        type: 'integer'
        #example: 2
        description: "对应的任务id"

  OptionRequest:
    type: 'object'
    properties:
      questionIndex:
        type: 'integer'
        description: '对应的问题在数组里的下标，从0开始'
      value:
        type: 'string'
        #example: '男的'
        description: '对于填空题，这个字段无效。
        对于选择题，这个字段就是选项的内容'

  Answer:
    type: 'object'
    properties:
      uid:
        type: 'integer'
      aid:
        type: 'integer'
      qid:
        type: 'integer'
      oid:
        type: 'integer'
      value:
        type: 'string'
      timestamp:
        type: 'string'

  AnswerRequest:
    type: 'object'
    properties:
      uid:
        type: 'integer'
        #example: 4
        description: '对应的用户id'
      qid:
        type: 'integer'
        #example: 1
        description: '对应的问题id'
      oid:
        type: 'integer'
        #example: 1
        description: '答案的对应的选项id,用于单选和多选'
      value:
        type: 'string'
        #example: 'ljm'
        description: '填空题输入的值'
      timestamp:
        type: 'string'
        #example: "2019-06-13 20:44:22"
        description: '填写时间'
  
  QuestionnaireInfoRequest:
    allOf:
    # - $ref: '#/definitions/AssignmentInfoResponse'
    - properties:
        title:
          type: 'string'
          example: '李泓睿知识大全'
        description:
          type: 'string'
          example: '关于李泓睿的问卷'
        # type: 
        #   type: 'string'
        #   enum:
        #   - 'questionnaire'
        # creator:
        #   type: 'integer'
        coin:
          description: '这个是单价，别填错了'
          type: 'integer'
          example: 5
        copy:
          description: '份数'
          type: 'integer'
          example: 100
        createTime:
          type: 'string'
          example: "2019-06-13 20:44:22"
        startTime:
          type: 'string'
          example: "2019-06-14 20:44:22"
        endTime:
          type: 'string'
          example: "2019-06-15 20:44:22"
        questions:
          type: 'array'
          items:
            allOf:
            - $ref: '#/definitions/QuestionRequest'

        options:
          description: '填空题也要添加选项字段'
          type: 'array'
          items:
            allOf:
            - $ref: '#/definitions/OptionRequest'
          example:
            - questionIndex: 0
              value: '男的'
            - questionIndex: 0
              value: '女的'

    # - properties:
    #     data:
    #       type: 'array'
    #       items:
    #         allOf:
    #         - $ref: '#/definitions/Question'
    #         - properties:
    #             data:
    #               type: 'array'
    #               items:
    #                 allOf:
    #                 - $ref: '#/definitions/Option'
            
  QuestionnaireInfoResponse:
    allOf:
    # - $ref: '#/definitions/AssignmentInfoResponse'
    - properties:
        title:
          type: 'string'
          example: '定向越野报名表'
        description:
          type: 'string'
          example: 'sdcs定向越野'
        type: 
          type: 'string'
          enum:
          - 'questionnaire'
        aid:
          type: 'integer'
          example: 2
          description: "对应的任务id"
        creator:
          type: 'string'
          example: 'm'
        coin:
          type: 'integer'
          example: 100
          description: "总价"
        unit:
          type: 'integer'
          example: 5  
          description: "单价"
        createTime:
          type: 'string'
          example: "2019-06-13 20:44:21"
        startTime:
          type: 'string'
          example: "2019-06-14 21:45:21"
        endTime:
          type: 'string'
          example: "2020-06-15 20:44:21"
   
        questions:
          type: 'array'
          items:
            allOf:
            - $ref: '#/definitions/Question'
          example:
            - qid: 1
              title: '姓名'
              aid: 2
              type: 'input'
            - qid: 2
              title: '性别'
              aid: 2
              type: 'single'
            - qid: 3
              title: '时间'
              aid: 2
              type: 'multi'
        options:
          type: 'array'
          items:
            allOf:
            - $ref: '#/definitions/Option'
          example:
            - oid: 1
              value: '0'
              qid: 1
              aid: 2
            - oid: 2
              value: '男'
              qid: 2
              aid: 2
            - oid: 3
              value: '女'
              qid: 2
              aid: 2
            - oid: 4
              value: '周六'
              qid: 3
              aid: 2
            - oid: 5
              value: '周日'
              qid: 3
              aid: 2



  AnswerInfoResponse:
    allOf:
      - $ref: '#/definitions/QuestionnaireInfoResponse'
      - properties:
          oid1:
            description: '这里的oid1指的是第一个每个对应选项的oid数字'
            type: 'array'
            items:
              type: 'object'
              properties:
                user:
                  type: 'string'
                  enum:
                  - 'UserID@Nickname'
                value:
                  type: 'string'
                  example: "ljm"
                timestamp:
                  type: 'string'
                  example: "2019-06-12 21:45:21"
          oid2:
            type: 'array'
            items:
              type: 'object'
              properties:
                user:
                  type: 'string'
                  enum:
                  - 'UserID@Nickname'
                  example: '4@ljm'
                value:
                  type: 'string'
                  example: "0"
                timestamp:
                  type: 'string'
                  example: "2019-06-12 21:45:21"


  QuestionnaireAnsRequest:
    type: 'object'
    properties:
      answers:
        type: 'array'
        items:
          allOf:
          - $ref: '#/definitions/AnswerRequest'
        example:
          - uid: 4
            qid: 1
            oid: 1
            value: 'ljm'
            timestamp: "2019-06-13 20:44:22"
          - uid: 4
            qid: 2
            oid: 2
            value: '0'
            timestamp: "2019-06-13 20:44:22"
          - uid: 4
            qid: 3
            oid: 4
            value: '0'
            timestamp: "2019-06-13 20:44:22"

  QAInfoRequest:
    allOf:
    # - $ref: '#/definitions/AssignmentInfoResponse'
    - properties:
        title:
          type: 'string'
          example: "李泓睿是谁"
        description:
          type: 'string'
          example: "最近看到有关他的问卷，不知道此人是谁"
        # type: 
        #   type: 'string'
        #   enum:
        #   - 'qa'
        # creator:
        #   type: 'integer'
        coin:
          type: 'integer'
          example: 50
        createTime:
          type: 'string'
          example: "2019-06-13 20:44:22"
        startTime:
          type: 'string'
          example: "2019-06-14 20:44:22"
        endTime:
          type: 'string'
          example: "2019-06-15 20:44:22"
        detail:
          type: 'string'
          example: "呵呵呵"

  QAnswerRequest:
    type: 'object'
    properties:
      # uid:
      #   type: 'integer'
      pid:
        type: 'integer'
        example: 1
      answer:
        type: 'string'
        example: "李泓睿同学肯定会，问他吧"
      timestamp:
        type: 'string'
        example: "2019-06-13 20:44:22"

  QAnswerResponse:
    type: 'object'
    properties:
      user:
        type: 'string'
        enum:
        - 'UserID@Nickname'
      aid:
        type: 'integer'
      qaid:
        type: 'integer'
      pid:
        type: 'integer'
      answer:
        type: 'string'
      timestamp:
        type: 'string'

  QAnswerBestResponse:
    type: 'object'
    properties:
      user:
        type: 'string'
        enum:
        - 'UserID@Nickname'
      aid:
        type: 'integer'
        example: 1
      pid:
        type: 'integer'
        example: 1
      answer:
        type: 'string'
        example: 'www.google.com'
      timestamp:
        type: 'string'
        example: "2019-06-21 20:59:21"

  QAnswerInfoRequest:
    type: 'array'
    items:
      allOf:
      - $ref: '#/definitions/QAnswerRequest'

  QAInfoResponse:
    allOf:
    # - $ref: '#/definitions/AssignmentInfoResponse'
    - properties:
        title:
          type: 'string'
          example: 'Vue怎么写'
        description:
          type: 'string'
          example: '请教教我写Vue'
        type: 
          type: 'string'
          enum:
          - 'qa'
        aid:
          type: 'integer'
          example: 1
          description: "对应的任务id"
        creator:
          type: 'string'
          example: 'm'
        coin:
          type: 'integer'
          example: 99
          description: "总价"
        createTime:
          type: 'string'
          example: "2019-06-11 20:44:21"
        startTime:
          type: 'string'
          example: "2019-06-11 21:45:21"
        endTime:
          type: 'string'
          example: "2020-06-12 20:44:21"
        pid:
          type: 'integer'
          example: 1
          description: "对应的问题id"
        detail:
          type: 'string'
          example: "我是刚学Vue的同学, 希望有人能教教我Vue"
        best:
          allOf:
          - $ref: '#/definitions/QAnswerBestResponse'
        answers:
          type: 'array'
          items:
            allOf:
            - $ref: '#/definitions/QAnswerResponse'
          example:
            - user: 'UserID@Nickname'
              aid: 1
              qaid: 1
              pid: 1
              answer: 'www.google.com'
              timestamp: "2019-06-21 20:59:21"
            - user: '4@ljm'
              aid: 1
              qaid: 2
              pid: 1
              answer: '一天速成'
              timestamp: "2019-06-21 20:59:21"

  IdResponse:
    type: 'object'
    properties:
      id:
        type: 'integer'
        example: 5
        
  RegisterResponse:
    allOf:
     - properties:
        msg:
          type: 'string'
          example: 'register successfully'
     - $ref: '#/definitions/IdResponse'

  CoinResponse:
    type: 'object'
    properties:
      coin:
        type: 'integer'
        example: 100

  CoinRequest:
    type: 'object'
    properties:
      coin:
        type: 'integer'

externalDocs:
  description: 'api.yaml'
  url: 'http://swagger.io'